jwt:
  secret: '[a-zA-Z0-0._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8082

spring:
  datasource:
    username: postgres
    password: sugeaPostgres
    url: jdbc:postgresql://localhost:5432/pg_elektron
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: pg-elektron.spring@gmail.com
    password: 0104E3DE156BC53AA33ADF47DA118BAC503E
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    #      javax:
    #        persistence:
    #          schema-generation:
    #            create-source: metadata
    #            scripts:
    #              action: create
    #              create-target: pg_elektron_database_create.sql
    show-sql: true
    database: postgresql


