jwt:
  secret: '[a-zA-Z0-0._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8082

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/pg_elektron

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    #      javax:
    #        persistence:
    #          schema-generation:
    #            create-source: metadata
    #            scripts:
    #              action: create
    #              create-target: pg_elektron_database_create.sql
    show-sql: true
    database: postgresql